### ISSUE TITLE
Remove `trim-newlines` dependency

### ISSUE THREAD

**Issue by ktschmincke** [sindresorhus/meow#219]
## Description
The `meow` package includes `trim-newlines` as a dependency (https://github.com/sindresorhus/trim-newlines). This dependency should be removed and the functionality recreated in `meow`.

## Purpose
Reducing dependencies reduces risk overall, and something as simple as trimming newlines should not be pulled in as a dependency.

**Comment by sindresorhus** [comment]
The package is not a trivial as you may think.

**Comment by sindresorhus** [comment]
> Reducing dependencies reduces risk overall

That's only true if the package comes from a different developer. Since I am the developer of both of this, inlining the dependency actually increases the risk. The package is more likely to receive improvements and security fixes as it has many consumers, while the inlined code will code rot and remain stale.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/meow/issues/67 is a better solution

**Comment by ktschmincke** [comment]
I clearly didn't look closely enough to realize you were the author of both 😅
