### ISSUE TITLE
Automatic alias parsing

### ISSUE THREAD

**Issue by adjohnson916** [sindresorhus/meow#24]
Meow could automatically parse aliases from the help text, e.g.:

```
...
Options
  -d, --dir        Directory
  -r, --recursive  Recursive
...
```

Results in effective configuration:

```
{
  alias: {
    d: 'dir',
    r: 'recursive'
  }
}
```

We could enable/disable this behavior with another option, disabled by default for backwards compatibility.

The implementation could start as a simple regular expression.

Let me know if you'd be open to a pull request.

**Comment by sindresorhus** [comment]
It's a cool idea. Not sure if it's a good fit here, though, as I'm trying to stay as unopinionated as possible. Gonna keep this open for a while to see if there's any interest in this.

In the meantime I made [`aliases`](https://github.com/sindresorhus/aliases) (which uses [`parse-help`](https://github.com/sindresorhus/parse-help)), so you can easily plug it into `meow`.

```js
const meow = require('meow');
const aliases = require('aliases');

const help = `
    Usage
      $ unicorn <name>

    Options
      -r, --rainbow  Lorem ipsum dolor sit amet
      -m, --magic    Aenean commodo ligula eget dolor
`;

meow(help, {
	alias: aliases(help, {h: 'help'})
})
```

-

*You could potentially also make a more opinionated `meow` wrapper with this.*

**Comment by SamVerschueren** [comment]
I like the idea, but rather don't want to see it implemented in `meow` directly. The solution of @sindresorhus is quite nice!

In my opinion, the implementation of the cli app is decoupled from the documentation of the app. Today, I choose for the `-r, --rainbow` notation. But maybe tomorrow I like `--rainbow (-r)` better. So if I change the documentation, my cli app breaks because I haven't thought about adding the `alias` property because my documentation format is not supported.

With the solution of @sindresorhus I can write my own parser for `--rainbow (-r)`. And if I want `-r, --rainbow` back, I can use the `aliases` module.

**Comment by corysimmons** [comment]
@adjohnson916 I see what you're saying but I don't think the cli should impose aliases based on what our help text looks like.

**Comment by adjohnson916** [comment]
Thanks @sindresorhus for creating [`aliases`](https://github.com/sindresorhus/aliases) based on my idea. Modular magic is to me an acceptable alternative to meow magic. Perhaps at some point we could include it in meow as an opt-in feature. If not, we should at least link to it from the README here.
