### ISSUE TITLE
commander?

### ISSUE THREAD

**Issue by ianstormtaylor** [sindresorhus/meow#32]
What's the advantages to using Meow instead of [`commander.js`](https://github.com/tj/commander.js/)?

**Comment by sindresorhus** [comment]
Meow only does the minimum thing most CLI's will need. It was pretty much just the common thing in all my CLI's extracted into a module. It's great for simple CLI's or when you need a lot of control. Otherwise `commander.js` is probably a better choice, or even better, [`yargs`](https://github.com/bcoe/yargs).

**Comment by yvele** [comment]
Or [neodoc](https://github.com/felixSchl/neodoc) (revised implementation of the [docopt language](http://docopt.org/))
