### ISSUE TITLE
meow-plus

### ISSUE THREAD

**Issue by mklabs** [sindresorhus/meow#38]
An idea, maybe totally silly.

I was thinking of bundling every little tools I use when creating a new CLI, sort of like meow does.

I would usually need everything meow does plus:

- A lightweight logger, ideally based on debug and npmlog
- tab completion, something like integrating tabtab here but with completion registered automatically from help output and parse-help
- chalk & log-symbos, maybe tightly integrated with the logger. I kinda like being able to do `Hello:red Sindre:bold` (`:color` used to escape strings with chalk methods)
- stdin helpers (#20)

I wonder if it is something that could go into meow directly, otherwise it will probably go into a `meow-plus` package.

😺

**Comment by sindresorhus** [comment]
Sounds like a good idea, but should be a separate project. `meow` is pretty much the result of me extracting what I had in common in most of my CLI's. I tried to keep it as minimal as possible. I would also go with something other than `meow-plus`. Since it's bigger, it should be a bigger cat sound, so maybe `roar`? :p (Btw, the name is taken, but it's name grabbed, so you can just request it from npm).

> A lightweight logger, ideally based on debug and npmlog

Maybe: https://github.com/kevva/squeak

> chalk & log-symbos, maybe tightly integrated with the logger. I kinda like being able to do Hello:red Sindre:bold (:color used to escape strings with chalk methods)

Not a big fan of that syntax. You might be able to take some inspiration from https://github.com/chalk/chalk-cli/pull/4 (when it's done).

> stdin helpers (#20)

I plan on probably adding this to `meow`. Just need to figure out the details. Feedback on #20 highly appreciated.

**Comment by mklabs** [comment]
Thanks a lot Sindre for all your inputs.

I wasn't aware of squeak, looks very nice and pretty much what I had in mind.

Really cool stuff with that chalk template feature. If it lands, it handles my need pretty nicely.

As for the name, I was thinking of `miaou` or something like that, which if the french equivalent of meow. I like `roar` as well, but I'd prefer avoid the hassle of requesting it.

Btw, I like your new meow avatar :p

**Comment by kevva** [comment]
@mklabs, if you end up using `squeak`, please do open issues if you think anything can be improved. I'm not too satisfied with it :P.

**Comment by sindresorhus** [comment]
`miaou` is hard to type though. I'll request `roar` for you if that's the only thing stopping you? It's a very easy process. You just email `abuse@npmjs.com` that the package is name-grabbed and they'll give it to you within a day or two. No drama.

**Comment by mklabs** [comment]
@kevva I have yet to use it, but I'll do :)

> I'm not too satisfied with it :P.

Why so ? Looks pretty cool, and minimal amount of dependencies which is what I'm looking for.

**Comment by mklabs** [comment]
I started working on this idea yesterday. Ended up with something like this (though its a bit tied to the tool i was writing): https://github.com/mklabs/bake/blob/master/lib/cli.js#L11

since I need to do the same for another one, I'll probably work on this again today and extract it into its own package.

@sindresorhus about the `roar` name, sure thing I'll maybe request the package name. Otherwise, I may go for something like `roar-cli`.

Feel free to close the issue if you'd like.
