### ISSUE TITLE
Allow subcommands to handle --help

### ISSUE THREAD

**Issue by arichardsmith** [sindresorhus/meow#62]
Currently when handling subcommands using separate meow instances like this:
```js
const bar = argv => {
	const cli = meow({
		argv,
		help: `
		  Usage
		    $ foo bar <input>
	`});
};

const cli = meow(`
	Usage
	  $ foo <command>

	Commands
	  bar
`);

// Check cli.input and handle commands
```
If the user enters ```$ foo bar --help``` they get the help for ```foo``` and not ```foo bar```

There's a wrapper called [moggie](https://github.com/florianb/moggie) that handles subcommands, but I was thinking we could to add a ```commands: [commands]``` option to meow so it doesn't block the --help flag?

Meow could either:
 - Not show help if a command is matched, leaving everything else to the user to handle
 - Handle the argv filtering and return the matched command and filtered argv

I'm happy to write something and submit a PR.

**Comment by angeloashmore** [comment]
Running into this issue now. A subcommand implements it's own meow instance with it's own help text.

Rather than providing a list of commands to meow, since that is a moggie-specific solution, maybe provide a toggle to turn off the automatic `--help` handler? The programmer could then handle how and when `showHelp()` is called.

I could submit a PR if necessary. Unless there is a better way to handle this with the existing options in meow or minimist?
